### ISSUE TITLE
`try {} catch {}` block redundant

### ISSUE THREAD

**Issue by maxatwork** [shystruk/publish-subscribe-js#1]
This and similar `try {} catch {}` blocks are redundant, they do nothing, because there are no error handling, just re-throw.

https://github.com/shystruk/publish-subscribe-js/blob/8a3467a1b3627875a93ad13e43191f1891f70702/src/PublishSubscribe.js#L55-L59

It also affects performance on V8 util version 6 because try {} catch excludes entire function from optimization, but this issue have been fixed in modern versions of V8, so it's just unnecessary code.

**Comment by shystruk** [comment]
Hi @maxatwork 
Good point.
In this case, try/catch helps to avoid error if a subscriber is not a function.
Yes, error logs should be improved.

**Comment by maxatwork** [comment]
> In this case, try/catch helps to avoid error if a subscriber is not a function.

It actually doesn't. You'll have the same exception with and without try ... catch.
It's better to check explicitly if subscriber is a function, and probably better to do it in subscribe (and throw there).

**Comment by shystruk** [comment]
Closed in commit - https://github.com/shystruk/publish-subscribe-js/commit/13f48f3128ec40860b0742531b4910f9ae21005f
